// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.23.1
// source: MqServerRpc.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Account_Mode int32

const (
	Account_root   Account_Mode = 0
	Account_normal Account_Mode = 1
)

// Enum value maps for Account_Mode.
var (
	Account_Mode_name = map[int32]string{
		0: "root",
		1: "normal",
	}
	Account_Mode_value = map[string]int32{
		"root":   0,
		"normal": 1,
	}
)

func (x Account_Mode) Enum() *Account_Mode {
	p := new(Account_Mode)
	*p = x
	return p
}

func (x Account_Mode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Account_Mode) Descriptor() protoreflect.EnumDescriptor {
	return file_MqServerRpc_proto_enumTypes[0].Descriptor()
}

func (Account_Mode) Type() protoreflect.EnumType {
	return &file_MqServerRpc_proto_enumTypes[0]
}

func (x Account_Mode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Account_Mode.Descriptor instead.
func (Account_Mode) EnumDescriptor() ([]byte, []int) {
	return file_MqServerRpc_proto_rawDescGZIP(), []int{0, 0}
}

type Response_ResponseMode int32

const (
	Response_Success        Response_ResponseMode = 0
	Response_Failure        Response_ResponseMode = 1
	Response_MetadataUpdate Response_ResponseMode = 2
	Response_PeerNoFind     Response_ResponseMode = 3
	Response_Timeout        Response_ResponseMode = 4
)

// Enum value maps for Response_ResponseMode.
var (
	Response_ResponseMode_name = map[int32]string{
		0: "Success",
		1: "Failure",
		2: "MetadataUpdate",
		3: "PeerNoFind",
		4: "Timeout",
	}
	Response_ResponseMode_value = map[string]int32{
		"Success":        0,
		"Failure":        1,
		"MetadataUpdate": 2,
		"PeerNoFind":     3,
		"Timeout":        4,
	}
)

func (x Response_ResponseMode) Enum() *Response_ResponseMode {
	p := new(Response_ResponseMode)
	*p = x
	return p
}

func (x Response_ResponseMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Response_ResponseMode) Descriptor() protoreflect.EnumDescriptor {
	return file_MqServerRpc_proto_enumTypes[1].Descriptor()
}

func (Response_ResponseMode) Type() protoreflect.EnumType {
	return &file_MqServerRpc_proto_enumTypes[1]
}

func (x Response_ResponseMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Response_ResponseMode.Descriptor instead.
func (Response_ResponseMode) EnumDescriptor() ([]byte, []int) {
	return file_MqServerRpc_proto_rawDescGZIP(), []int{3, 0}
}

type Account struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name     string `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=Password,proto3" json:"Password,omitempty"`
}

func (x *Account) Reset() {
	*x = Account{}
	if protoimpl.UnsafeEnabled {
		mi := &file_MqServerRpc_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Account) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Account) ProtoMessage() {}

func (x *Account) ProtoReflect() protoreflect.Message {
	mi := &file_MqServerRpc_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Account.ProtoReflect.Descriptor instead.
func (*Account) Descriptor() ([]byte, []int) {
	return file_MqServerRpc_proto_rawDescGZIP(), []int{0}
}

func (x *Account) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Account) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	X  *Account `protobuf:"bytes,2,opt,name=_,proto3" json:"_,omitempty"`
	Id int64    `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
}

func (x *Request) Reset() {
	*x = Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_MqServerRpc_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_MqServerRpc_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_MqServerRpc_proto_rawDescGZIP(), []int{1}
}

func (x *Request) GetX() *Account {
	if x != nil {
		return x.X
	}
	return nil
}

func (x *Request) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type Message struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data      []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Timestamp string `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
}

func (x *Message) Reset() {
	*x = Message{}
	if protoimpl.UnsafeEnabled {
		mi := &file_MqServerRpc_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_MqServerRpc_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_MqServerRpc_proto_rawDescGZIP(), []int{2}
}

func (x *Message) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Message) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

type Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mode Response_ResponseMode `protobuf:"varint,1,opt,name=mode,proto3,enum=MqServer.Response_ResponseMode" json:"mode,omitempty"`
}

func (x *Response) Reset() {
	*x = Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_MqServerRpc_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_MqServerRpc_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_MqServerRpc_proto_rawDescGZIP(), []int{3}
}

func (x *Response) GetMode() Response_ResponseMode {
	if x != nil {
		return x.Mode
	}
	return Response_Success
}

type RegisterConsumerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	X              *Request `protobuf:"bytes,10,opt,name=_,proto3" json:"_,omitempty"`
	Topic          string   `protobuf:"bytes,1,opt,name=Topic,proto3" json:"Topic,omitempty"`
	Partition      string   `protobuf:"bytes,2,opt,name=Partition,proto3" json:"Partition,omitempty"`
	GroupId        string   `protobuf:"bytes,3,opt,name=GroupId,proto3" json:"GroupId,omitempty"`
	MaxPullRecords int32    `protobuf:"varint,4,opt,name=MaxPullRecords,proto3" json:"MaxPullRecords,omitempty"`
	SessionMs      int32    `protobuf:"varint,5,opt,name=Session_ms,json=SessionMs,proto3" json:"Session_ms,omitempty"`
}

func (x *RegisterConsumerRequest) Reset() {
	*x = RegisterConsumerRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_MqServerRpc_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterConsumerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterConsumerRequest) ProtoMessage() {}

func (x *RegisterConsumerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_MqServerRpc_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterConsumerRequest.ProtoReflect.Descriptor instead.
func (*RegisterConsumerRequest) Descriptor() ([]byte, []int) {
	return file_MqServerRpc_proto_rawDescGZIP(), []int{4}
}

func (x *RegisterConsumerRequest) GetX() *Request {
	if x != nil {
		return x.X
	}
	return nil
}

func (x *RegisterConsumerRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *RegisterConsumerRequest) GetPartition() string {
	if x != nil {
		return x.Partition
	}
	return ""
}

func (x *RegisterConsumerRequest) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *RegisterConsumerRequest) GetMaxPullRecords() int32 {
	if x != nil {
		return x.MaxPullRecords
	}
	return 0
}

func (x *RegisterConsumerRequest) GetSessionMs() int32 {
	if x != nil {
		return x.SessionMs
	}
	return 0
}

type RegisterConsumerResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	X         *Response `protobuf:"bytes,1,opt,name=_,proto3" json:"_,omitempty"`
	Id        int64     `protobuf:"varint,2,opt,name=Id,proto3" json:"Id,omitempty"`
	Topic     string    `protobuf:"bytes,3,opt,name=Topic,proto3" json:"Topic,omitempty"`
	Partition string    `protobuf:"bytes,4,opt,name=Partition,proto3" json:"Partition,omitempty"`
}

func (x *RegisterConsumerResponse) Reset() {
	*x = RegisterConsumerResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_MqServerRpc_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterConsumerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterConsumerResponse) ProtoMessage() {}

func (x *RegisterConsumerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_MqServerRpc_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterConsumerResponse.ProtoReflect.Descriptor instead.
func (*RegisterConsumerResponse) Descriptor() ([]byte, []int) {
	return file_MqServerRpc_proto_rawDescGZIP(), []int{5}
}

func (x *RegisterConsumerResponse) GetX() *Response {
	if x != nil {
		return x.X
	}
	return nil
}

func (x *RegisterConsumerResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *RegisterConsumerResponse) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *RegisterConsumerResponse) GetPartition() string {
	if x != nil {
		return x.Partition
	}
	return ""
}

type Ack struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	X      *Account `protobuf:"bytes,2,opt,name=_,proto3" json:"_,omitempty"`
	Offset int64    `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
}

func (x *Ack) Reset() {
	*x = Ack{}
	if protoimpl.UnsafeEnabled {
		mi := &file_MqServerRpc_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_MqServerRpc_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_MqServerRpc_proto_rawDescGZIP(), []int{6}
}

func (x *Ack) GetX() *Account {
	if x != nil {
		return x.X
	}
	return nil
}

func (x *Ack) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type PullMessageRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	X         *Request `protobuf:"bytes,1,opt,name=_,proto3" json:"_,omitempty"`
	Topic     string   `protobuf:"bytes,2,opt,name=Topic,proto3" json:"Topic,omitempty"`
	Partition string   `protobuf:"bytes,3,opt,name=Partition,proto3" json:"Partition,omitempty"`
}

func (x *PullMessageRequest) Reset() {
	*x = PullMessageRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_MqServerRpc_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PullMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullMessageRequest) ProtoMessage() {}

func (x *PullMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_MqServerRpc_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PullMessageRequest.ProtoReflect.Descriptor instead.
func (*PullMessageRequest) Descriptor() ([]byte, []int) {
	return file_MqServerRpc_proto_rawDescGZIP(), []int{7}
}

func (x *PullMessageRequest) GetX() *Request {
	if x != nil {
		return x.X
	}
	return nil
}

func (x *PullMessageRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *PullMessageRequest) GetPartition() string {
	if x != nil {
		return x.Partition
	}
	return ""
}

type PushMessageRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	X       *Request   `protobuf:"bytes,1,opt,name=_,proto3" json:"_,omitempty"`
	Message []*Message `protobuf:"bytes,2,rep,name=message,proto3" json:"message,omitempty"`
}

func (x *PushMessageRequest) Reset() {
	*x = PushMessageRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_MqServerRpc_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PushMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushMessageRequest) ProtoMessage() {}

func (x *PushMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_MqServerRpc_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushMessageRequest.ProtoReflect.Descriptor instead.
func (*PushMessageRequest) Descriptor() ([]byte, []int) {
	return file_MqServerRpc_proto_rawDescGZIP(), []int{8}
}

func (x *PushMessageRequest) GetX() *Request {
	if x != nil {
		return x.X
	}
	return nil
}

func (x *PushMessageRequest) GetMessage() []*Message {
	if x != nil {
		return x.Message
	}
	return nil
}

type PullMessageResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	X       *Response  `protobuf:"bytes,1,opt,name=_,proto3" json:"_,omitempty"`
	Message []*Message `protobuf:"bytes,2,rep,name=message,proto3" json:"message,omitempty"`
}

func (x *PullMessageResponse) Reset() {
	*x = PullMessageResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_MqServerRpc_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PullMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullMessageResponse) ProtoMessage() {}

func (x *PullMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_MqServerRpc_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PullMessageResponse.ProtoReflect.Descriptor instead.
func (*PullMessageResponse) Descriptor() ([]byte, []int) {
	return file_MqServerRpc_proto_rawDescGZIP(), []int{9}
}

func (x *PullMessageResponse) GetX() *Response {
	if x != nil {
		return x.X
	}
	return nil
}

func (x *PullMessageResponse) GetMessage() []*Message {
	if x != nil {
		return x.Message
	}
	return nil
}

type PushMessageResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	X *Response `protobuf:"bytes,1,opt,name=_,proto3" json:"_,omitempty"`
}

func (x *PushMessageResponse) Reset() {
	*x = PushMessageResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_MqServerRpc_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PushMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushMessageResponse) ProtoMessage() {}

func (x *PushMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_MqServerRpc_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushMessageResponse.ProtoReflect.Descriptor instead.
func (*PushMessageResponse) Descriptor() ([]byte, []int) {
	return file_MqServerRpc_proto_rawDescGZIP(), []int{10}
}

func (x *PushMessageResponse) GetX() *Response {
	if x != nil {
		return x.X
	}
	return nil
}

type RegisterProducerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	X          *Request `protobuf:"bytes,1,opt,name=_,proto3" json:"_,omitempty"`
	Topic      string   `protobuf:"bytes,2,opt,name=Topic,proto3" json:"Topic,omitempty"`
	Copyable   bool     `protobuf:"varint,3,opt,name=Copyable,proto3" json:"Copyable,omitempty"`
	CopyNumber int32    `protobuf:"varint,4,opt,name=CopyNumber,proto3" json:"CopyNumber,omitempty"`
}

func (x *RegisterProducerRequest) Reset() {
	*x = RegisterProducerRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_MqServerRpc_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterProducerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterProducerRequest) ProtoMessage() {}

func (x *RegisterProducerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_MqServerRpc_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterProducerRequest.ProtoReflect.Descriptor instead.
func (*RegisterProducerRequest) Descriptor() ([]byte, []int) {
	return file_MqServerRpc_proto_rawDescGZIP(), []int{11}
}

func (x *RegisterProducerRequest) GetX() *Request {
	if x != nil {
		return x.X
	}
	return nil
}

func (x *RegisterProducerRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *RegisterProducerRequest) GetCopyable() bool {
	if x != nil {
		return x.Copyable
	}
	return false
}

func (x *RegisterProducerRequest) GetCopyNumber() int32 {
	if x != nil {
		return x.CopyNumber
	}
	return 0
}

type RegisterProducerResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	X  *Response `protobuf:"bytes,1,opt,name=_,proto3" json:"_,omitempty"`
	Id int64     `protobuf:"varint,2,opt,name=Id,proto3" json:"Id,omitempty"`
}

func (x *RegisterProducerResponse) Reset() {
	*x = RegisterProducerResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_MqServerRpc_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterProducerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterProducerResponse) ProtoMessage() {}

func (x *RegisterProducerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_MqServerRpc_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterProducerResponse.ProtoReflect.Descriptor instead.
func (*RegisterProducerResponse) Descriptor() ([]byte, []int) {
	return file_MqServerRpc_proto_rawDescGZIP(), []int{12}
}

func (x *RegisterProducerResponse) GetX() *Response {
	if x != nil {
		return x.X
	}
	return nil
}

func (x *RegisterProducerResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type UpdateMetadataRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	X            *Request `protobuf:"bytes,1,opt,name=_,proto3" json:"_,omitempty"`
	MetadataTerm int32    `protobuf:"varint,2,opt,name=MetadataTerm,proto3" json:"MetadataTerm,omitempty"`
}

func (x *UpdateMetadataRequest) Reset() {
	*x = UpdateMetadataRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_MqServerRpc_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateMetadataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMetadataRequest) ProtoMessage() {}

func (x *UpdateMetadataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_MqServerRpc_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMetadataRequest.ProtoReflect.Descriptor instead.
func (*UpdateMetadataRequest) Descriptor() ([]byte, []int) {
	return file_MqServerRpc_proto_rawDescGZIP(), []int{13}
}

func (x *UpdateMetadataRequest) GetX() *Request {
	if x != nil {
		return x.X
	}
	return nil
}

func (x *UpdateMetadataRequest) GetMetadataTerm() int32 {
	if x != nil {
		return x.MetadataTerm
	}
	return 0
}

type Tp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Topic     string `protobuf:"bytes,1,opt,name=Topic,proto3" json:"Topic,omitempty"`
	Partition string `protobuf:"bytes,2,opt,name=Partition,proto3" json:"Partition,omitempty"`
	Url       string `protobuf:"bytes,3,opt,name=Url,proto3" json:"Url,omitempty"`
}

func (x *Tp) Reset() {
	*x = Tp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_MqServerRpc_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Tp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tp) ProtoMessage() {}

func (x *Tp) ProtoReflect() protoreflect.Message {
	mi := &file_MqServerRpc_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tp.ProtoReflect.Descriptor instead.
func (*Tp) Descriptor() ([]byte, []int) {
	return file_MqServerRpc_proto_rawDescGZIP(), []int{14}
}

func (x *Tp) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *Tp) GetPartition() string {
	if x != nil {
		return x.Partition
	}
	return ""
}

func (x *Tp) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type ClientFocusInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tps []*Tp `protobuf:"bytes,1,rep,name=Tps,proto3" json:"Tps,omitempty"`
}

func (x *ClientFocusInfo) Reset() {
	*x = ClientFocusInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_MqServerRpc_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientFocusInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientFocusInfo) ProtoMessage() {}

func (x *ClientFocusInfo) ProtoReflect() protoreflect.Message {
	mi := &file_MqServerRpc_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientFocusInfo.ProtoReflect.Descriptor instead.
func (*ClientFocusInfo) Descriptor() ([]byte, []int) {
	return file_MqServerRpc_proto_rawDescGZIP(), []int{15}
}

func (x *ClientFocusInfo) GetTps() []*Tp {
	if x != nil {
		return x.Tps
	}
	return nil
}

// 是 针对 某个Id(C/P) 进行的 元数据查询
type UpdateMetadataResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	X            *Response        `protobuf:"bytes,1,opt,name=_,proto3" json:"_,omitempty"`
	Info         *ClientFocusInfo `protobuf:"bytes,2,opt,name=Info,proto3" json:"Info,omitempty"`
	MetadataTerm int32            `protobuf:"varint,3,opt,name=MetadataTerm,proto3" json:"MetadataTerm,omitempty"`
}

func (x *UpdateMetadataResponse) Reset() {
	*x = UpdateMetadataResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_MqServerRpc_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateMetadataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMetadataResponse) ProtoMessage() {}

func (x *UpdateMetadataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_MqServerRpc_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMetadataResponse.ProtoReflect.Descriptor instead.
func (*UpdateMetadataResponse) Descriptor() ([]byte, []int) {
	return file_MqServerRpc_proto_rawDescGZIP(), []int{16}
}

func (x *UpdateMetadataResponse) GetX() *Response {
	if x != nil {
		return x.X
	}
	return nil
}

func (x *UpdateMetadataResponse) GetInfo() *ClientFocusInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

func (x *UpdateMetadataResponse) GetMetadataTerm() int32 {
	if x != nil {
		return x.MetadataTerm
	}
	return 0
}

var File_MqServerRpc_proto protoreflect.FileDescriptor

var file_MqServerRpc_proto_rawDesc = []byte{
	0x0a, 0x11, 0x4d, 0x71, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x52, 0x70, 0x63, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x08, 0x4d, 0x71, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x22, 0x57, 0x0a,
	0x07, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08,
	0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x22, 0x1c, 0x0a, 0x04, 0x4d, 0x6f, 0x64, 0x65,
	0x12, 0x08, 0x0a, 0x04, 0x72, 0x6f, 0x6f, 0x74, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x6e, 0x6f,
	0x72, 0x6d, 0x61, 0x6c, 0x10, 0x01, 0x22, 0x39, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x1e, 0x0a, 0x01, 0x5f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x4d,
	0x71, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x52,
	0x00, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x49,
	0x64, 0x22, 0x3b, 0x0a, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x22, 0x9a,
	0x01, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x33, 0x0a, 0x04, 0x6d,
	0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1f, 0x2e, 0x4d, 0x71, 0x53, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x4d, 0x6f, 0x64, 0x65, 0x52, 0x04, 0x6d, 0x6f, 0x64, 0x65,
	0x22, 0x59, 0x0a, 0x0c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x4d, 0x6f, 0x64, 0x65,
	0x12, 0x0b, 0x0a, 0x07, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x10, 0x00, 0x12, 0x0b, 0x0a,
	0x07, 0x46, 0x61, 0x69, 0x6c, 0x75, 0x72, 0x65, 0x10, 0x01, 0x12, 0x12, 0x0a, 0x0e, 0x4d, 0x65,
	0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x10, 0x02, 0x12, 0x0e,
	0x0a, 0x0a, 0x50, 0x65, 0x65, 0x72, 0x4e, 0x6f, 0x46, 0x69, 0x6e, 0x64, 0x10, 0x03, 0x12, 0x0b,
	0x0a, 0x07, 0x54, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x10, 0x04, 0x22, 0xce, 0x01, 0x0a, 0x17,
	0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x43, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65, 0x72,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1e, 0x0a, 0x01, 0x5f, 0x18, 0x0a, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x11, 0x2e, 0x4d, 0x71, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x00, 0x12, 0x14, 0x0a, 0x05, 0x54, 0x6f, 0x70, 0x69, 0x63,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x54, 0x6f, 0x70, 0x69, 0x63, 0x12, 0x1c, 0x0a,
	0x09, 0x50, 0x61, 0x72, 0x74, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x50, 0x61, 0x72, 0x74, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x47,
	0x72, 0x6f, 0x75, 0x70, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x47, 0x72,
	0x6f, 0x75, 0x70, 0x49, 0x64, 0x12, 0x26, 0x0a, 0x0e, 0x4d, 0x61, 0x78, 0x50, 0x75, 0x6c, 0x6c,
	0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0e, 0x4d,
	0x61, 0x78, 0x50, 0x75, 0x6c, 0x6c, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x73, 0x12, 0x1d, 0x0a,
	0x0a, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x6d, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x09, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x4d, 0x73, 0x22, 0x7f, 0x0a, 0x18,
	0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x43, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65, 0x72,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1f, 0x0a, 0x01, 0x5f, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x4d, 0x71, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x00, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x54, 0x6f, 0x70,
	0x69, 0x63, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x54, 0x6f, 0x70, 0x69, 0x63, 0x12,
	0x1c, 0x0a, 0x09, 0x50, 0x61, 0x72, 0x74, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x50, 0x61, 0x72, 0x74, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x3d, 0x0a,
	0x03, 0x41, 0x63, 0x6b, 0x12, 0x1e, 0x0a, 0x01, 0x5f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x11, 0x2e, 0x4d, 0x71, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x41, 0x63, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x52, 0x00, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x22, 0x68, 0x0a, 0x12,
	0x50, 0x75, 0x6c, 0x6c, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x1e, 0x0a, 0x01, 0x5f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e,
	0x4d, 0x71, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x52, 0x00, 0x12, 0x14, 0x0a, 0x05, 0x54, 0x6f, 0x70, 0x69, 0x63, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x54, 0x6f, 0x70, 0x69, 0x63, 0x12, 0x1c, 0x0a, 0x09, 0x50, 0x61, 0x72, 0x74,
	0x69, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x50, 0x61, 0x72,
	0x74, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x61, 0x0a, 0x12, 0x50, 0x75, 0x73, 0x68, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1e, 0x0a, 0x01,
	0x5f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x4d, 0x71, 0x53, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x00, 0x12, 0x2b, 0x0a, 0x07,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e,
	0x4d, 0x71, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x63, 0x0a, 0x13, 0x50, 0x75, 0x6c,
	0x6c, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x1f, 0x0a, 0x01, 0x5f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x4d, 0x71,
	0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52,
	0x00, 0x12, 0x2b, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x11, 0x2e, 0x4d, 0x71, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x36,
	0x0a, 0x13, 0x50, 0x75, 0x73, 0x68, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1f, 0x0a, 0x01, 0x5f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x12, 0x2e, 0x4d, 0x71, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x52, 0x00, 0x22, 0x8b, 0x01, 0x0a, 0x17, 0x52, 0x65, 0x67, 0x69, 0x73,
	0x74, 0x65, 0x72, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x1e, 0x0a, 0x01, 0x5f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e,
	0x4d, 0x71, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x52, 0x00, 0x12, 0x14, 0x0a, 0x05, 0x54, 0x6f, 0x70, 0x69, 0x63, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x54, 0x6f, 0x70, 0x69, 0x63, 0x12, 0x1a, 0x0a, 0x08, 0x43, 0x6f, 0x70, 0x79,
	0x61, 0x62, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x43, 0x6f, 0x70, 0x79,
	0x61, 0x62, 0x6c, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x43, 0x6f, 0x70, 0x79, 0x4e, 0x75, 0x6d, 0x62,
	0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x43, 0x6f, 0x70, 0x79, 0x4e, 0x75,
	0x6d, 0x62, 0x65, 0x72, 0x22, 0x4b, 0x0a, 0x18, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72,
	0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x1f, 0x0a, 0x01, 0x5f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x4d, 0x71,
	0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52,
	0x00, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x49,
	0x64, 0x22, 0x5b, 0x0a, 0x15, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4d, 0x65, 0x74, 0x61, 0x64,
	0x61, 0x74, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1e, 0x0a, 0x01, 0x5f, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x4d, 0x71, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x00, 0x12, 0x22, 0x0a, 0x0c, 0x4d, 0x65,
	0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x54, 0x65, 0x72, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x0c, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x54, 0x65, 0x72, 0x6d, 0x22, 0x4a,
	0x0a, 0x02, 0x54, 0x70, 0x12, 0x14, 0x0a, 0x05, 0x54, 0x6f, 0x70, 0x69, 0x63, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x54, 0x6f, 0x70, 0x69, 0x63, 0x12, 0x1c, 0x0a, 0x09, 0x50, 0x61,
	0x72, 0x74, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x50,
	0x61, 0x72, 0x74, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x55, 0x72, 0x6c, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x55, 0x72, 0x6c, 0x22, 0x31, 0x0a, 0x0f, 0x43, 0x6c,
	0x69, 0x65, 0x6e, 0x74, 0x46, 0x6f, 0x63, 0x75, 0x73, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1e, 0x0a,
	0x03, 0x54, 0x70, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x4d, 0x71, 0x53,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x54, 0x70, 0x52, 0x03, 0x54, 0x70, 0x73, 0x22, 0x8c, 0x01,
	0x0a, 0x16, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1f, 0x0a, 0x01, 0x5f, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x4d, 0x71, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x00, 0x12, 0x2d, 0x0a, 0x04, 0x49, 0x6e, 0x66,
	0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x4d, 0x71, 0x53, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x46, 0x6f, 0x63, 0x75, 0x73, 0x49, 0x6e,
	0x66, 0x6f, 0x52, 0x04, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x22, 0x0a, 0x0c, 0x4d, 0x65, 0x74, 0x61,
	0x64, 0x61, 0x74, 0x61, 0x54, 0x65, 0x72, 0x6d, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c,
	0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x54, 0x65, 0x72, 0x6d, 0x32, 0xed, 0x03, 0x0a,
	0x0c, 0x4d, 0x71, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x43, 0x61, 0x6c, 0x6c, 0x12, 0x30, 0x0a,
	0x09, 0x48, 0x65, 0x61, 0x72, 0x74, 0x62, 0x65, 0x61, 0x74, 0x12, 0x0d, 0x2e, 0x4d, 0x71, 0x53,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x41, 0x63, 0x6b, 0x1a, 0x12, 0x2e, 0x4d, 0x71, 0x53, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12,
	0x5b, 0x0a, 0x10, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x43, 0x6f, 0x6e, 0x73, 0x75,
	0x6d, 0x65, 0x72, 0x12, 0x21, 0x2e, 0x4d, 0x71, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x52,
	0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x43, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65, 0x72, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x4d, 0x71, 0x53, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x43, 0x6f, 0x6e, 0x73, 0x75, 0x6d,
	0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x5b, 0x0a, 0x10,
	0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x65, 0x72,
	0x12, 0x21, 0x2e, 0x4d, 0x71, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x52, 0x65, 0x67, 0x69,
	0x73, 0x74, 0x65, 0x72, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x4d, 0x71, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x52,
	0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x65, 0x72, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x4c, 0x0a, 0x0b, 0x50, 0x75, 0x6c,
	0x6c, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x1c, 0x2e, 0x4d, 0x71, 0x53, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x2e, 0x50, 0x75, 0x6c, 0x6c, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x4d, 0x71, 0x53, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x2e, 0x50, 0x75, 0x6c, 0x6c, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x4c, 0x0a, 0x0b, 0x50, 0x75, 0x73, 0x68, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x1c, 0x2e, 0x4d, 0x71, 0x53, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x2e, 0x50, 0x75, 0x73, 0x68, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x4d, 0x71, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e,
	0x50, 0x75, 0x73, 0x68, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x55, 0x0a, 0x0e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4d,
	0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x12, 0x1f, 0x2e, 0x4d, 0x71, 0x53, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74,
	0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x4d, 0x71, 0x53, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61,
	0x74, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x03, 0x5a, 0x01,
	0x2e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_MqServerRpc_proto_rawDescOnce sync.Once
	file_MqServerRpc_proto_rawDescData = file_MqServerRpc_proto_rawDesc
)

func file_MqServerRpc_proto_rawDescGZIP() []byte {
	file_MqServerRpc_proto_rawDescOnce.Do(func() {
		file_MqServerRpc_proto_rawDescData = protoimpl.X.CompressGZIP(file_MqServerRpc_proto_rawDescData)
	})
	return file_MqServerRpc_proto_rawDescData
}

var file_MqServerRpc_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_MqServerRpc_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_MqServerRpc_proto_goTypes = []interface{}{
	(Account_Mode)(0),                // 0: MqServer.Account.Mode
	(Response_ResponseMode)(0),       // 1: MqServer.Response.ResponseMode
	(*Account)(nil),                  // 2: MqServer.Account
	(*Request)(nil),                  // 3: MqServer.Request
	(*Message)(nil),                  // 4: MqServer.Message
	(*Response)(nil),                 // 5: MqServer.Response
	(*RegisterConsumerRequest)(nil),  // 6: MqServer.RegisterConsumerRequest
	(*RegisterConsumerResponse)(nil), // 7: MqServer.RegisterConsumerResponse
	(*Ack)(nil),                      // 8: MqServer.Ack
	(*PullMessageRequest)(nil),       // 9: MqServer.PullMessageRequest
	(*PushMessageRequest)(nil),       // 10: MqServer.PushMessageRequest
	(*PullMessageResponse)(nil),      // 11: MqServer.PullMessageResponse
	(*PushMessageResponse)(nil),      // 12: MqServer.PushMessageResponse
	(*RegisterProducerRequest)(nil),  // 13: MqServer.RegisterProducerRequest
	(*RegisterProducerResponse)(nil), // 14: MqServer.RegisterProducerResponse
	(*UpdateMetadataRequest)(nil),    // 15: MqServer.UpdateMetadataRequest
	(*Tp)(nil),                       // 16: MqServer.Tp
	(*ClientFocusInfo)(nil),          // 17: MqServer.ClientFocusInfo
	(*UpdateMetadataResponse)(nil),   // 18: MqServer.UpdateMetadataResponse
}
var file_MqServerRpc_proto_depIdxs = []int32{
	2,  // 0: MqServer.Request._:type_name -> MqServer.Account
	1,  // 1: MqServer.Response.mode:type_name -> MqServer.Response.ResponseMode
	3,  // 2: MqServer.RegisterConsumerRequest._:type_name -> MqServer.Request
	5,  // 3: MqServer.RegisterConsumerResponse._:type_name -> MqServer.Response
	2,  // 4: MqServer.Ack._:type_name -> MqServer.Account
	3,  // 5: MqServer.PullMessageRequest._:type_name -> MqServer.Request
	3,  // 6: MqServer.PushMessageRequest._:type_name -> MqServer.Request
	4,  // 7: MqServer.PushMessageRequest.message:type_name -> MqServer.Message
	5,  // 8: MqServer.PullMessageResponse._:type_name -> MqServer.Response
	4,  // 9: MqServer.PullMessageResponse.message:type_name -> MqServer.Message
	5,  // 10: MqServer.PushMessageResponse._:type_name -> MqServer.Response
	3,  // 11: MqServer.RegisterProducerRequest._:type_name -> MqServer.Request
	5,  // 12: MqServer.RegisterProducerResponse._:type_name -> MqServer.Response
	3,  // 13: MqServer.UpdateMetadataRequest._:type_name -> MqServer.Request
	16, // 14: MqServer.ClientFocusInfo.Tps:type_name -> MqServer.Tp
	5,  // 15: MqServer.UpdateMetadataResponse._:type_name -> MqServer.Response
	17, // 16: MqServer.UpdateMetadataResponse.Info:type_name -> MqServer.ClientFocusInfo
	8,  // 17: MqServer.MqServerCall.Heartbeat:input_type -> MqServer.Ack
	6,  // 18: MqServer.MqServerCall.RegisterConsumer:input_type -> MqServer.RegisterConsumerRequest
	13, // 19: MqServer.MqServerCall.RegisterProducer:input_type -> MqServer.RegisterProducerRequest
	9,  // 20: MqServer.MqServerCall.PullMessage:input_type -> MqServer.PullMessageRequest
	10, // 21: MqServer.MqServerCall.PushMessage:input_type -> MqServer.PushMessageRequest
	15, // 22: MqServer.MqServerCall.UpdateMetadata:input_type -> MqServer.UpdateMetadataRequest
	5,  // 23: MqServer.MqServerCall.Heartbeat:output_type -> MqServer.Response
	7,  // 24: MqServer.MqServerCall.RegisterConsumer:output_type -> MqServer.RegisterConsumerResponse
	14, // 25: MqServer.MqServerCall.RegisterProducer:output_type -> MqServer.RegisterProducerResponse
	11, // 26: MqServer.MqServerCall.PullMessage:output_type -> MqServer.PullMessageResponse
	12, // 27: MqServer.MqServerCall.PushMessage:output_type -> MqServer.PushMessageResponse
	18, // 28: MqServer.MqServerCall.UpdateMetadata:output_type -> MqServer.UpdateMetadataResponse
	23, // [23:29] is the sub-list for method output_type
	17, // [17:23] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_MqServerRpc_proto_init() }
func file_MqServerRpc_proto_init() {
	if File_MqServerRpc_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_MqServerRpc_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Account); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_MqServerRpc_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_MqServerRpc_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Message); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_MqServerRpc_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_MqServerRpc_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterConsumerRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_MqServerRpc_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterConsumerResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_MqServerRpc_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Ack); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_MqServerRpc_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PullMessageRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_MqServerRpc_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PushMessageRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_MqServerRpc_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PullMessageResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_MqServerRpc_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PushMessageResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_MqServerRpc_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterProducerRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_MqServerRpc_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterProducerResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_MqServerRpc_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateMetadataRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_MqServerRpc_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Tp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_MqServerRpc_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientFocusInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_MqServerRpc_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateMetadataResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_MqServerRpc_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_MqServerRpc_proto_goTypes,
		DependencyIndexes: file_MqServerRpc_proto_depIdxs,
		EnumInfos:         file_MqServerRpc_proto_enumTypes,
		MessageInfos:      file_MqServerRpc_proto_msgTypes,
	}.Build()
	File_MqServerRpc_proto = out.File
	file_MqServerRpc_proto_rawDesc = nil
	file_MqServerRpc_proto_goTypes = nil
	file_MqServerRpc_proto_depIdxs = nil
}
