// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.23.1
// source: MqServerRpc.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Credentials_CredentialsIdentity int32

const (
	Credentials_Consumer Credentials_CredentialsIdentity = 0
	Credentials_Producer Credentials_CredentialsIdentity = 1
	Credentials_Broker   Credentials_CredentialsIdentity = 2
)

// Enum value maps for Credentials_CredentialsIdentity.
var (
	Credentials_CredentialsIdentity_name = map[int32]string{
		0: "Consumer",
		1: "Producer",
		2: "Broker",
	}
	Credentials_CredentialsIdentity_value = map[string]int32{
		"Consumer": 0,
		"Producer": 1,
		"Broker":   2,
	}
)

func (x Credentials_CredentialsIdentity) Enum() *Credentials_CredentialsIdentity {
	p := new(Credentials_CredentialsIdentity)
	*p = x
	return p
}

func (x Credentials_CredentialsIdentity) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Credentials_CredentialsIdentity) Descriptor() protoreflect.EnumDescriptor {
	return file_MqServerRpc_proto_enumTypes[0].Descriptor()
}

func (Credentials_CredentialsIdentity) Type() protoreflect.EnumType {
	return &file_MqServerRpc_proto_enumTypes[0]
}

func (x Credentials_CredentialsIdentity) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Credentials_CredentialsIdentity.Descriptor instead.
func (Credentials_CredentialsIdentity) EnumDescriptor() ([]byte, []int) {
	return file_MqServerRpc_proto_rawDescGZIP(), []int{0, 0}
}

type Response_Mode int32

const (
	Response_Success               Response_Mode = 0
	Response_Failure               Response_Mode = 1
	Response_ErrTimeout            Response_Mode = 8
	Response_ErrNotLeader          Response_Mode = 7
	Response_ErrSourceNotExist     Response_Mode = 2
	Response_ErrSourceAlreadyExist Response_Mode = 6
	Response_ErrPartitionChanged   Response_Mode = 3
	Response_ErrRequestIllegal     Response_Mode = 4
	Response_ErrSourceNotEnough    Response_Mode = 5
)

// Enum value maps for Response_Mode.
var (
	Response_Mode_name = map[int32]string{
		0: "Success",
		1: "Failure",
		8: "ErrTimeout",
		7: "ErrNotLeader",
		2: "ErrSourceNotExist",
		6: "ErrSourceAlreadyExist",
		3: "ErrPartitionChanged",
		4: "ErrRequestIllegal",
		5: "ErrSourceNotEnough",
	}
	Response_Mode_value = map[string]int32{
		"Success":               0,
		"Failure":               1,
		"ErrTimeout":            8,
		"ErrNotLeader":          7,
		"ErrSourceNotExist":     2,
		"ErrSourceAlreadyExist": 6,
		"ErrPartitionChanged":   3,
		"ErrRequestIllegal":     4,
		"ErrSourceNotEnough":    5,
	}
)

func (x Response_Mode) Enum() *Response_Mode {
	p := new(Response_Mode)
	*p = x
	return p
}

func (x Response_Mode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Response_Mode) Descriptor() protoreflect.EnumDescriptor {
	return file_MqServerRpc_proto_enumTypes[1].Descriptor()
}

func (Response_Mode) Type() protoreflect.EnumType {
	return &file_MqServerRpc_proto_enumTypes[1]
}

func (x Response_Mode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Response_Mode.Descriptor instead.
func (Response_Mode) EnumDescriptor() ([]byte, []int) {
	return file_MqServerRpc_proto_rawDescGZIP(), []int{2, 0}
}

type RegisterConsumerRequest_OffsetReset int32

const (
	RegisterConsumerRequest_Earliest RegisterConsumerRequest_OffsetReset = 0
	RegisterConsumerRequest_Latest   RegisterConsumerRequest_OffsetReset = 1
	RegisterConsumerRequest_None     RegisterConsumerRequest_OffsetReset = 2
)

// Enum value maps for RegisterConsumerRequest_OffsetReset.
var (
	RegisterConsumerRequest_OffsetReset_name = map[int32]string{
		0: "Earliest",
		1: "Latest",
		2: "None",
	}
	RegisterConsumerRequest_OffsetReset_value = map[string]int32{
		"Earliest": 0,
		"Latest":   1,
		"None":     2,
	}
)

func (x RegisterConsumerRequest_OffsetReset) Enum() *RegisterConsumerRequest_OffsetReset {
	p := new(RegisterConsumerRequest_OffsetReset)
	*p = x
	return p
}

func (x RegisterConsumerRequest_OffsetReset) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RegisterConsumerRequest_OffsetReset) Descriptor() protoreflect.EnumDescriptor {
	return file_MqServerRpc_proto_enumTypes[2].Descriptor()
}

func (RegisterConsumerRequest_OffsetReset) Type() protoreflect.EnumType {
	return &file_MqServerRpc_proto_enumTypes[2]
}

func (x RegisterConsumerRequest_OffsetReset) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RegisterConsumerRequest_OffsetReset.Descriptor instead.
func (RegisterConsumerRequest_OffsetReset) EnumDescriptor() ([]byte, []int) {
	return file_MqServerRpc_proto_rawDescGZIP(), []int{3, 0}
}

type ManagePartitionRequest_ManageModes int32

const (
	ManagePartitionRequest_Add      ManagePartitionRequest_ManageModes = 0
	ManagePartitionRequest_Del      ManagePartitionRequest_ManageModes = 1
	ManagePartitionRequest_Follow   ManagePartitionRequest_ManageModes = 2
	ManagePartitionRequest_UnFollow ManagePartitionRequest_ManageModes = 3
)

// Enum value maps for ManagePartitionRequest_ManageModes.
var (
	ManagePartitionRequest_ManageModes_name = map[int32]string{
		0: "Add",
		1: "Del",
		2: "Follow",
		3: "UnFollow",
	}
	ManagePartitionRequest_ManageModes_value = map[string]int32{
		"Add":      0,
		"Del":      1,
		"Follow":   2,
		"UnFollow": 3,
	}
)

func (x ManagePartitionRequest_ManageModes) Enum() *ManagePartitionRequest_ManageModes {
	p := new(ManagePartitionRequest_ManageModes)
	*p = x
	return p
}

func (x ManagePartitionRequest_ManageModes) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ManagePartitionRequest_ManageModes) Descriptor() protoreflect.EnumDescriptor {
	return file_MqServerRpc_proto_enumTypes[3].Descriptor()
}

func (ManagePartitionRequest_ManageModes) Type() protoreflect.EnumType {
	return &file_MqServerRpc_proto_enumTypes[3]
}

func (x ManagePartitionRequest_ManageModes) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ManagePartitionRequest_ManageModes.Descriptor instead.
func (ManagePartitionRequest_ManageModes) EnumDescriptor() ([]byte, []int) {
	return file_MqServerRpc_proto_rawDescGZIP(), []int{23, 0}
}

// 凭证/通过这个找到对应的Consumer
type Credentials struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Identity Credentials_CredentialsIdentity `protobuf:"varint,1,opt,name=Identity,proto3,enum=MqServer.Credentials_CredentialsIdentity" json:"Identity,omitempty"`
	Id       uint32                          `protobuf:"varint,2,opt,name=Id,proto3" json:"Id,omitempty"`
	Hash     int64                           `protobuf:"varint,3,opt,name=Hash,proto3" json:"Hash,omitempty"`
}

func (x *Credentials) Reset() {
	*x = Credentials{}
	if protoimpl.UnsafeEnabled {
		mi := &file_MqServerRpc_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Credentials) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Credentials) ProtoMessage() {}

func (x *Credentials) ProtoReflect() protoreflect.Message {
	mi := &file_MqServerRpc_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Credentials.ProtoReflect.Descriptor instead.
func (*Credentials) Descriptor() ([]byte, []int) {
	return file_MqServerRpc_proto_rawDescGZIP(), []int{0}
}

func (x *Credentials) GetIdentity() Credentials_CredentialsIdentity {
	if x != nil {
		return x.Identity
	}
	return Credentials_Consumer
}

func (x *Credentials) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Credentials) GetHash() int64 {
	if x != nil {
		return x.Hash
	}
	return 0
}

type Ack struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Credential *Credentials `protobuf:"bytes,1,opt,name=credential,proto3" json:"credential,omitempty"`
	// Consumer's receive message offset
	Offset *int32 `protobuf:"varint,2,opt,name=offset,proto3,oneof" json:"offset,omitempty"`
}

func (x *Ack) Reset() {
	*x = Ack{}
	if protoimpl.UnsafeEnabled {
		mi := &file_MqServerRpc_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_MqServerRpc_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_MqServerRpc_proto_rawDescGZIP(), []int{1}
}

func (x *Ack) GetCredential() *Credentials {
	if x != nil {
		return x.Credential
	}
	return nil
}

func (x *Ack) GetOffset() int32 {
	if x != nil && x.Offset != nil {
		return *x.Offset
	}
	return 0
}

type Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mode Response_Mode `protobuf:"varint,1,opt,name=mode,proto3,enum=MqServer.Response_Mode" json:"mode,omitempty"`
}

func (x *Response) Reset() {
	*x = Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_MqServerRpc_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_MqServerRpc_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_MqServerRpc_proto_rawDescGZIP(), []int{2}
}

func (x *Response) GetMode() Response_Mode {
	if x != nil {
		return x.Mode
	}
	return Response_Success
}

type RegisterConsumerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FocalTopic string `protobuf:"bytes,1,opt,name=FocalTopic,proto3" json:"FocalTopic,omitempty"`
	// empty for all
	FocalPartitions      []string                            `protobuf:"bytes,2,rep,name=FocalPartitions,proto3" json:"FocalPartitions,omitempty"`
	MaxReturnMessageSize int32                               `protobuf:"varint,3,opt,name=MaxReturnMessageSize,proto3" json:"MaxReturnMessageSize,omitempty"`
	TimeoutSessionMsec   int32                               `protobuf:"varint,4,opt,name=timeoutSessionMsec,proto3" json:"timeoutSessionMsec,omitempty"`
	OffsetResetMode      RegisterConsumerRequest_OffsetReset `protobuf:"varint,5,opt,name=OffsetResetMode,proto3,enum=MqServer.RegisterConsumerRequest_OffsetReset" json:"OffsetResetMode,omitempty"`
}

func (x *RegisterConsumerRequest) Reset() {
	*x = RegisterConsumerRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_MqServerRpc_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterConsumerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterConsumerRequest) ProtoMessage() {}

func (x *RegisterConsumerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_MqServerRpc_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterConsumerRequest.ProtoReflect.Descriptor instead.
func (*RegisterConsumerRequest) Descriptor() ([]byte, []int) {
	return file_MqServerRpc_proto_rawDescGZIP(), []int{3}
}

func (x *RegisterConsumerRequest) GetFocalTopic() string {
	if x != nil {
		return x.FocalTopic
	}
	return ""
}

func (x *RegisterConsumerRequest) GetFocalPartitions() []string {
	if x != nil {
		return x.FocalPartitions
	}
	return nil
}

func (x *RegisterConsumerRequest) GetMaxReturnMessageSize() int32 {
	if x != nil {
		return x.MaxReturnMessageSize
	}
	return 0
}

func (x *RegisterConsumerRequest) GetTimeoutSessionMsec() int32 {
	if x != nil {
		return x.TimeoutSessionMsec
	}
	return 0
}

func (x *RegisterConsumerRequest) GetOffsetResetMode() RegisterConsumerRequest_OffsetReset {
	if x != nil {
		return x.OffsetResetMode
	}
	return RegisterConsumerRequest_Earliest
}

type Partition struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Topic string `protobuf:"bytes,1,opt,name=Topic,proto3" json:"Topic,omitempty"`
	Name  string `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Url   string `protobuf:"bytes,3,opt,name=Url,proto3" json:"Url,omitempty"`
}

func (x *Partition) Reset() {
	*x = Partition{}
	if protoimpl.UnsafeEnabled {
		mi := &file_MqServerRpc_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Partition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Partition) ProtoMessage() {}

func (x *Partition) ProtoReflect() protoreflect.Message {
	mi := &file_MqServerRpc_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Partition.ProtoReflect.Descriptor instead.
func (*Partition) Descriptor() ([]byte, []int) {
	return file_MqServerRpc_proto_rawDescGZIP(), []int{4}
}

func (x *Partition) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *Partition) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Partition) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type RegisterConsumerResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Response        *Response    `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	Credential      *Credentials `protobuf:"bytes,2,opt,name=Credential,proto3" json:"Credential,omitempty"`
	FocalPartitions []*Partition `protobuf:"bytes,3,rep,name=FocalPartitions,proto3" json:"FocalPartitions,omitempty"`
}

func (x *RegisterConsumerResponse) Reset() {
	*x = RegisterConsumerResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_MqServerRpc_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterConsumerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterConsumerResponse) ProtoMessage() {}

func (x *RegisterConsumerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_MqServerRpc_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterConsumerResponse.ProtoReflect.Descriptor instead.
func (*RegisterConsumerResponse) Descriptor() ([]byte, []int) {
	return file_MqServerRpc_proto_rawDescGZIP(), []int{5}
}

func (x *RegisterConsumerResponse) GetResponse() *Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *RegisterConsumerResponse) GetCredential() *Credentials {
	if x != nil {
		return x.Credential
	}
	return nil
}

func (x *RegisterConsumerResponse) GetFocalPartitions() []*Partition {
	if x != nil {
		return x.FocalPartitions
	}
	return nil
}

type RegisterProducerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FocalTopic string `protobuf:"bytes,1,opt,name=FocalTopic,proto3" json:"FocalTopic,omitempty"`
	// int32 TimeoutSessionMsec = 2;
	MaxPushMessageSize int32 `protobuf:"varint,3,opt,name=MaxPushMessageSize,proto3" json:"MaxPushMessageSize,omitempty"`
}

func (x *RegisterProducerRequest) Reset() {
	*x = RegisterProducerRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_MqServerRpc_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterProducerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterProducerRequest) ProtoMessage() {}

func (x *RegisterProducerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_MqServerRpc_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterProducerRequest.ProtoReflect.Descriptor instead.
func (*RegisterProducerRequest) Descriptor() ([]byte, []int) {
	return file_MqServerRpc_proto_rawDescGZIP(), []int{6}
}

func (x *RegisterProducerRequest) GetFocalTopic() string {
	if x != nil {
		return x.FocalTopic
	}
	return ""
}

func (x *RegisterProducerRequest) GetMaxPushMessageSize() int32 {
	if x != nil {
		return x.MaxPushMessageSize
	}
	return 0
}

type RegisterProducerResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Response              *Response    `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	Credential            *Credentials `protobuf:"bytes,2,opt,name=Credential,proto3" json:"Credential,omitempty"`
	FocalPartitions       []*Partition `protobuf:"bytes,3,rep,name=FocalPartitions,proto3" json:"FocalPartitions,omitempty"`
	AllowPushMessageSize  int32        `protobuf:"varint,4,opt,name=AllowPushMessageSize,proto3" json:"AllowPushMessageSize,omitempty"`
	AllowPushMessageCount int32        `protobuf:"varint,5,opt,name=AllowPushMessageCount,proto3" json:"AllowPushMessageCount,omitempty"`
}

func (x *RegisterProducerResponse) Reset() {
	*x = RegisterProducerResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_MqServerRpc_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterProducerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterProducerResponse) ProtoMessage() {}

func (x *RegisterProducerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_MqServerRpc_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterProducerResponse.ProtoReflect.Descriptor instead.
func (*RegisterProducerResponse) Descriptor() ([]byte, []int) {
	return file_MqServerRpc_proto_rawDescGZIP(), []int{7}
}

func (x *RegisterProducerResponse) GetResponse() *Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *RegisterProducerResponse) GetCredential() *Credentials {
	if x != nil {
		return x.Credential
	}
	return nil
}

func (x *RegisterProducerResponse) GetFocalPartitions() []*Partition {
	if x != nil {
		return x.FocalPartitions
	}
	return nil
}

func (x *RegisterProducerResponse) GetAllowPushMessageSize() int32 {
	if x != nil {
		return x.AllowPushMessageSize
	}
	return 0
}

func (x *RegisterProducerResponse) GetAllowPushMessageCount() int32 {
	if x != nil {
		return x.AllowPushMessageCount
	}
	return 0
}

type CreateTopicRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Topic     string                                       `protobuf:"bytes,1,opt,name=Topic,proto3" json:"Topic,omitempty"`
	Partition []*CreateTopicRequest_PartitionCreateDetails `protobuf:"bytes,3,rep,name=Partition,proto3" json:"Partition,omitempty"`
}

func (x *CreateTopicRequest) Reset() {
	*x = CreateTopicRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_MqServerRpc_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateTopicRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTopicRequest) ProtoMessage() {}

func (x *CreateTopicRequest) ProtoReflect() protoreflect.Message {
	mi := &file_MqServerRpc_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTopicRequest.ProtoReflect.Descriptor instead.
func (*CreateTopicRequest) Descriptor() ([]byte, []int) {
	return file_MqServerRpc_proto_rawDescGZIP(), []int{8}
}

func (x *CreateTopicRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *CreateTopicRequest) GetPartition() []*CreateTopicRequest_PartitionCreateDetails {
	if x != nil {
		return x.Partition
	}
	return nil
}

type CreateTopicResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Response         *Response    `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	PartitionDetails []*Partition `protobuf:"bytes,2,rep,name=PartitionDetails,proto3" json:"PartitionDetails,omitempty"`
}

func (x *CreateTopicResponse) Reset() {
	*x = CreateTopicResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_MqServerRpc_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateTopicResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTopicResponse) ProtoMessage() {}

func (x *CreateTopicResponse) ProtoReflect() protoreflect.Message {
	mi := &file_MqServerRpc_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTopicResponse.ProtoReflect.Descriptor instead.
func (*CreateTopicResponse) Descriptor() ([]byte, []int) {
	return file_MqServerRpc_proto_rawDescGZIP(), []int{9}
}

func (x *CreateTopicResponse) GetResponse() *Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *CreateTopicResponse) GetPartitionDetails() []*Partition {
	if x != nil {
		return x.PartitionDetails
	}
	return nil
}

type QueryTopicRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Credential *Credentials `protobuf:"bytes,2,opt,name=credential,proto3" json:"credential,omitempty"`
	Topic      string       `protobuf:"bytes,1,opt,name=Topic,proto3" json:"Topic,omitempty"`
}

func (x *QueryTopicRequest) Reset() {
	*x = QueryTopicRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_MqServerRpc_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryTopicRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryTopicRequest) ProtoMessage() {}

func (x *QueryTopicRequest) ProtoReflect() protoreflect.Message {
	mi := &file_MqServerRpc_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryTopicRequest.ProtoReflect.Descriptor instead.
func (*QueryTopicRequest) Descriptor() ([]byte, []int) {
	return file_MqServerRpc_proto_rawDescGZIP(), []int{10}
}

func (x *QueryTopicRequest) GetCredential() *Credentials {
	if x != nil {
		return x.Credential
	}
	return nil
}

func (x *QueryTopicRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

type QueryTopicResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Response         *Response    `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	PartitionDetails []*Partition `protobuf:"bytes,2,rep,name=PartitionDetails,proto3" json:"PartitionDetails,omitempty"`
}

func (x *QueryTopicResponse) Reset() {
	*x = QueryTopicResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_MqServerRpc_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryTopicResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryTopicResponse) ProtoMessage() {}

func (x *QueryTopicResponse) ProtoReflect() protoreflect.Message {
	mi := &file_MqServerRpc_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryTopicResponse.ProtoReflect.Descriptor instead.
func (*QueryTopicResponse) Descriptor() ([]byte, []int) {
	return file_MqServerRpc_proto_rawDescGZIP(), []int{11}
}

func (x *QueryTopicResponse) GetResponse() *Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *QueryTopicResponse) GetPartitionDetails() []*Partition {
	if x != nil {
		return x.PartitionDetails
	}
	return nil
}

type DestroyTopicRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Topic string `protobuf:"bytes,1,opt,name=Topic,proto3" json:"Topic,omitempty"`
}

func (x *DestroyTopicRequest) Reset() {
	*x = DestroyTopicRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_MqServerRpc_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DestroyTopicRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DestroyTopicRequest) ProtoMessage() {}

func (x *DestroyTopicRequest) ProtoReflect() protoreflect.Message {
	mi := &file_MqServerRpc_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DestroyTopicRequest.ProtoReflect.Descriptor instead.
func (*DestroyTopicRequest) Descriptor() ([]byte, []int) {
	return file_MqServerRpc_proto_rawDescGZIP(), []int{12}
}

func (x *DestroyTopicRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

type DestroyTopicResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Response *Response `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
}

func (x *DestroyTopicResponse) Reset() {
	*x = DestroyTopicResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_MqServerRpc_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DestroyTopicResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DestroyTopicResponse) ProtoMessage() {}

func (x *DestroyTopicResponse) ProtoReflect() protoreflect.Message {
	mi := &file_MqServerRpc_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DestroyTopicResponse.ProtoReflect.Descriptor instead.
func (*DestroyTopicResponse) Descriptor() ([]byte, []int) {
	return file_MqServerRpc_proto_rawDescGZIP(), []int{13}
}

func (x *DestroyTopicResponse) GetResponse() *Response {
	if x != nil {
		return x.Response
	}
	return nil
}

type UnRegisterConsumerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Credential *Credentials `protobuf:"bytes,1,opt,name=credential,proto3" json:"credential,omitempty"`
}

func (x *UnRegisterConsumerRequest) Reset() {
	*x = UnRegisterConsumerRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_MqServerRpc_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UnRegisterConsumerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnRegisterConsumerRequest) ProtoMessage() {}

func (x *UnRegisterConsumerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_MqServerRpc_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnRegisterConsumerRequest.ProtoReflect.Descriptor instead.
func (*UnRegisterConsumerRequest) Descriptor() ([]byte, []int) {
	return file_MqServerRpc_proto_rawDescGZIP(), []int{14}
}

func (x *UnRegisterConsumerRequest) GetCredential() *Credentials {
	if x != nil {
		return x.Credential
	}
	return nil
}

type UnRegisterConsumerResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Response *Response `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
}

func (x *UnRegisterConsumerResponse) Reset() {
	*x = UnRegisterConsumerResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_MqServerRpc_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UnRegisterConsumerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnRegisterConsumerResponse) ProtoMessage() {}

func (x *UnRegisterConsumerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_MqServerRpc_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnRegisterConsumerResponse.ProtoReflect.Descriptor instead.
func (*UnRegisterConsumerResponse) Descriptor() ([]byte, []int) {
	return file_MqServerRpc_proto_rawDescGZIP(), []int{15}
}

func (x *UnRegisterConsumerResponse) GetResponse() *Response {
	if x != nil {
		return x.Response
	}
	return nil
}

type UnRegisterProducerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Credential *Credentials `protobuf:"bytes,1,opt,name=credential,proto3" json:"credential,omitempty"`
}

func (x *UnRegisterProducerRequest) Reset() {
	*x = UnRegisterProducerRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_MqServerRpc_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UnRegisterProducerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnRegisterProducerRequest) ProtoMessage() {}

func (x *UnRegisterProducerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_MqServerRpc_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnRegisterProducerRequest.ProtoReflect.Descriptor instead.
func (*UnRegisterProducerRequest) Descriptor() ([]byte, []int) {
	return file_MqServerRpc_proto_rawDescGZIP(), []int{16}
}

func (x *UnRegisterProducerRequest) GetCredential() *Credentials {
	if x != nil {
		return x.Credential
	}
	return nil
}

type UnRegisterProducerResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Response *Response `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
}

func (x *UnRegisterProducerResponse) Reset() {
	*x = UnRegisterProducerResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_MqServerRpc_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UnRegisterProducerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnRegisterProducerResponse) ProtoMessage() {}

func (x *UnRegisterProducerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_MqServerRpc_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnRegisterProducerResponse.ProtoReflect.Descriptor instead.
func (*UnRegisterProducerResponse) Descriptor() ([]byte, []int) {
	return file_MqServerRpc_proto_rawDescGZIP(), []int{17}
}

func (x *UnRegisterProducerResponse) GetResponse() *Response {
	if x != nil {
		return x.Response
	}
	return nil
}

type Message struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=Message,proto3" json:"Message,omitempty"`
}

func (x *Message) Reset() {
	*x = Message{}
	if protoimpl.UnsafeEnabled {
		mi := &file_MqServerRpc_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_MqServerRpc_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_MqServerRpc_proto_rawDescGZIP(), []int{18}
}

func (x *Message) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type PushMessageRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Credential *Credentials `protobuf:"bytes,1,opt,name=credential,proto3" json:"credential,omitempty"`
	Msgs       []*Message   `protobuf:"bytes,2,rep,name=Msgs,proto3" json:"Msgs,omitempty"`
}

func (x *PushMessageRequest) Reset() {
	*x = PushMessageRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_MqServerRpc_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PushMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushMessageRequest) ProtoMessage() {}

func (x *PushMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_MqServerRpc_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushMessageRequest.ProtoReflect.Descriptor instead.
func (*PushMessageRequest) Descriptor() ([]byte, []int) {
	return file_MqServerRpc_proto_rawDescGZIP(), []int{19}
}

func (x *PushMessageRequest) GetCredential() *Credentials {
	if x != nil {
		return x.Credential
	}
	return nil
}

func (x *PushMessageRequest) GetMsgs() []*Message {
	if x != nil {
		return x.Msgs
	}
	return nil
}

type PushMessageResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Response *Response `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
}

func (x *PushMessageResponse) Reset() {
	*x = PushMessageResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_MqServerRpc_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PushMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushMessageResponse) ProtoMessage() {}

func (x *PushMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_MqServerRpc_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushMessageResponse.ProtoReflect.Descriptor instead.
func (*PushMessageResponse) Descriptor() ([]byte, []int) {
	return file_MqServerRpc_proto_rawDescGZIP(), []int{20}
}

func (x *PushMessageResponse) GetResponse() *Response {
	if x != nil {
		return x.Response
	}
	return nil
}

type PullMessageRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	X          *Ack  `protobuf:"bytes,1,opt,name=_,proto3" json:"_,omitempty"`
	WindowSize int32 `protobuf:"varint,2,opt,name=WindowSize,proto3" json:"WindowSize,omitempty"`
}

func (x *PullMessageRequest) Reset() {
	*x = PullMessageRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_MqServerRpc_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PullMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullMessageRequest) ProtoMessage() {}

func (x *PullMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_MqServerRpc_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PullMessageRequest.ProtoReflect.Descriptor instead.
func (*PullMessageRequest) Descriptor() ([]byte, []int) {
	return file_MqServerRpc_proto_rawDescGZIP(), []int{21}
}

func (x *PullMessageRequest) GetX() *Ack {
	if x != nil {
		return x.X
	}
	return nil
}

func (x *PullMessageRequest) GetWindowSize() int32 {
	if x != nil {
		return x.WindowSize
	}
	return 0
}

type PullMessageResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Response *Response  `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	Msgs     []*Message `protobuf:"bytes,2,rep,name=Msgs,proto3" json:"Msgs,omitempty"`
}

func (x *PullMessageResponse) Reset() {
	*x = PullMessageResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_MqServerRpc_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PullMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullMessageResponse) ProtoMessage() {}

func (x *PullMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_MqServerRpc_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PullMessageResponse.ProtoReflect.Descriptor instead.
func (*PullMessageResponse) Descriptor() ([]byte, []int) {
	return file_MqServerRpc_proto_rawDescGZIP(), []int{22}
}

func (x *PullMessageResponse) GetResponse() *Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *PullMessageResponse) GetMsgs() []*Message {
	if x != nil {
		return x.Msgs
	}
	return nil
}

type ManagePartitionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Topic               string                             `protobuf:"bytes,1,opt,name=Topic,proto3" json:"Topic,omitempty"`
	ManageMode          ManagePartitionRequest_ManageModes `protobuf:"varint,2,opt,name=ManageMode,proto3,enum=MqServer.ManagePartitionRequest_ManageModes" json:"ManageMode,omitempty"`
	Credential          *Credentials                       `protobuf:"bytes,3,opt,name=Credential,proto3,oneof" json:"Credential,omitempty"`
	TargetPartitionName string                             `protobuf:"bytes,4,opt,name=TargetPartitionName,proto3" json:"TargetPartitionName,omitempty"`
}

func (x *ManagePartitionRequest) Reset() {
	*x = ManagePartitionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_MqServerRpc_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ManagePartitionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManagePartitionRequest) ProtoMessage() {}

func (x *ManagePartitionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_MqServerRpc_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManagePartitionRequest.ProtoReflect.Descriptor instead.
func (*ManagePartitionRequest) Descriptor() ([]byte, []int) {
	return file_MqServerRpc_proto_rawDescGZIP(), []int{23}
}

func (x *ManagePartitionRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *ManagePartitionRequest) GetManageMode() ManagePartitionRequest_ManageModes {
	if x != nil {
		return x.ManageMode
	}
	return ManagePartitionRequest_Add
}

func (x *ManagePartitionRequest) GetCredential() *Credentials {
	if x != nil {
		return x.Credential
	}
	return nil
}

func (x *ManagePartitionRequest) GetTargetPartitionName() string {
	if x != nil {
		return x.TargetPartitionName
	}
	return ""
}

type ManagePartitionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Response      *Response    `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	NowPartitions []*Partition `protobuf:"bytes,2,rep,name=NowPartitions,proto3" json:"NowPartitions,omitempty"`
}

func (x *ManagePartitionResponse) Reset() {
	*x = ManagePartitionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_MqServerRpc_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ManagePartitionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManagePartitionResponse) ProtoMessage() {}

func (x *ManagePartitionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_MqServerRpc_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManagePartitionResponse.ProtoReflect.Descriptor instead.
func (*ManagePartitionResponse) Descriptor() ([]byte, []int) {
	return file_MqServerRpc_proto_rawDescGZIP(), []int{24}
}

func (x *ManagePartitionResponse) GetResponse() *Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *ManagePartitionResponse) GetNowPartitions() []*Partition {
	if x != nil {
		return x.NowPartitions
	}
	return nil
}

type CreateTopicRequest_PartitionCreateDetails struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PartitionName     string `protobuf:"bytes,1,opt,name=PartitionName,proto3" json:"PartitionName,omitempty"`
	ReplicationNumber int32  `protobuf:"varint,2,opt,name=ReplicationNumber,proto3" json:"ReplicationNumber,omitempty"`
}

func (x *CreateTopicRequest_PartitionCreateDetails) Reset() {
	*x = CreateTopicRequest_PartitionCreateDetails{}
	if protoimpl.UnsafeEnabled {
		mi := &file_MqServerRpc_proto_msgTypes[25]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateTopicRequest_PartitionCreateDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTopicRequest_PartitionCreateDetails) ProtoMessage() {}

func (x *CreateTopicRequest_PartitionCreateDetails) ProtoReflect() protoreflect.Message {
	mi := &file_MqServerRpc_proto_msgTypes[25]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTopicRequest_PartitionCreateDetails.ProtoReflect.Descriptor instead.
func (*CreateTopicRequest_PartitionCreateDetails) Descriptor() ([]byte, []int) {
	return file_MqServerRpc_proto_rawDescGZIP(), []int{8, 0}
}

func (x *CreateTopicRequest_PartitionCreateDetails) GetPartitionName() string {
	if x != nil {
		return x.PartitionName
	}
	return ""
}

func (x *CreateTopicRequest_PartitionCreateDetails) GetReplicationNumber() int32 {
	if x != nil {
		return x.ReplicationNumber
	}
	return 0
}

var File_MqServerRpc_proto protoreflect.FileDescriptor

var file_MqServerRpc_proto_rawDesc = []byte{
	0x0a, 0x11, 0x4d, 0x71, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x52, 0x70, 0x63, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x08, 0x4d, 0x71, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x22, 0xb7, 0x01,
	0x0a, 0x0b, 0x43, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x73, 0x12, 0x45, 0x0a,
	0x08, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x29, 0x2e, 0x4d, 0x71, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x43, 0x72, 0x65, 0x64, 0x65,
	0x6e, 0x74, 0x69, 0x61, 0x6c, 0x73, 0x2e, 0x43, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61,
	0x6c, 0x73, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x52, 0x08, 0x49, 0x64, 0x65, 0x6e,
	0x74, 0x69, 0x74, 0x79, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x02, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x48, 0x61, 0x73, 0x68, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x04, 0x48, 0x61, 0x73, 0x68, 0x22, 0x3d, 0x0a, 0x13, 0x43, 0x72, 0x65, 0x64,
	0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x73, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x12,
	0x0c, 0x0a, 0x08, 0x43, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65, 0x72, 0x10, 0x00, 0x12, 0x0c, 0x0a,
	0x08, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x65, 0x72, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x42,
	0x72, 0x6f, 0x6b, 0x65, 0x72, 0x10, 0x02, 0x22, 0x64, 0x0a, 0x03, 0x41, 0x63, 0x6b, 0x12, 0x35,
	0x0a, 0x0a, 0x63, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x15, 0x2e, 0x4d, 0x71, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x43, 0x72,
	0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x73, 0x52, 0x0a, 0x63, 0x72, 0x65, 0x64, 0x65,
	0x6e, 0x74, 0x69, 0x61, 0x6c, 0x12, 0x1b, 0x0a, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x05, 0x48, 0x00, 0x52, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x88,
	0x01, 0x01, 0x42, 0x09, 0x0a, 0x07, 0x5f, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x22, 0xf6, 0x01,
	0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2b, 0x0a, 0x04, 0x6d, 0x6f,
	0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x17, 0x2e, 0x4d, 0x71, 0x53, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x4d, 0x6f, 0x64,
	0x65, 0x52, 0x04, 0x6d, 0x6f, 0x64, 0x65, 0x22, 0xbc, 0x01, 0x0a, 0x04, 0x4d, 0x6f, 0x64, 0x65,
	0x12, 0x0b, 0x0a, 0x07, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x10, 0x00, 0x12, 0x0b, 0x0a,
	0x07, 0x46, 0x61, 0x69, 0x6c, 0x75, 0x72, 0x65, 0x10, 0x01, 0x12, 0x0e, 0x0a, 0x0a, 0x45, 0x72,
	0x72, 0x54, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x10, 0x08, 0x12, 0x10, 0x0a, 0x0c, 0x45, 0x72,
	0x72, 0x4e, 0x6f, 0x74, 0x4c, 0x65, 0x61, 0x64, 0x65, 0x72, 0x10, 0x07, 0x12, 0x15, 0x0a, 0x11,
	0x45, 0x72, 0x72, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x4e, 0x6f, 0x74, 0x45, 0x78, 0x69, 0x73,
	0x74, 0x10, 0x02, 0x12, 0x19, 0x0a, 0x15, 0x45, 0x72, 0x72, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65,
	0x41, 0x6c, 0x72, 0x65, 0x61, 0x64, 0x79, 0x45, 0x78, 0x69, 0x73, 0x74, 0x10, 0x06, 0x12, 0x17,
	0x0a, 0x13, 0x45, 0x72, 0x72, 0x50, 0x61, 0x72, 0x74, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x68,
	0x61, 0x6e, 0x67, 0x65, 0x64, 0x10, 0x03, 0x12, 0x15, 0x0a, 0x11, 0x45, 0x72, 0x72, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x6c, 0x6c, 0x65, 0x67, 0x61, 0x6c, 0x10, 0x04, 0x12, 0x16,
	0x0a, 0x12, 0x45, 0x72, 0x72, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x4e, 0x6f, 0x74, 0x45, 0x6e,
	0x6f, 0x75, 0x67, 0x68, 0x10, 0x05, 0x22, 0xd3, 0x02, 0x0a, 0x17, 0x52, 0x65, 0x67, 0x69, 0x73,
	0x74, 0x65, 0x72, 0x43, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x46, 0x6f, 0x63, 0x61, 0x6c, 0x54, 0x6f, 0x70, 0x69, 0x63,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x46, 0x6f, 0x63, 0x61, 0x6c, 0x54, 0x6f, 0x70,
	0x69, 0x63, 0x12, 0x28, 0x0a, 0x0f, 0x46, 0x6f, 0x63, 0x61, 0x6c, 0x50, 0x61, 0x72, 0x74, 0x69,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0f, 0x46, 0x6f, 0x63,
	0x61, 0x6c, 0x50, 0x61, 0x72, 0x74, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x32, 0x0a, 0x14,
	0x4d, 0x61, 0x78, 0x52, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x53, 0x69, 0x7a, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x14, 0x4d, 0x61, 0x78, 0x52,
	0x65, 0x74, 0x75, 0x72, 0x6e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65,
	0x12, 0x2e, 0x0a, 0x12, 0x74, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x53, 0x65, 0x73, 0x73, 0x69,
	0x6f, 0x6e, 0x4d, 0x73, 0x65, 0x63, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x12, 0x74, 0x69,
	0x6d, 0x65, 0x6f, 0x75, 0x74, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x4d, 0x73, 0x65, 0x63,
	0x12, 0x57, 0x0a, 0x0f, 0x4f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x52, 0x65, 0x73, 0x65, 0x74, 0x4d,
	0x6f, 0x64, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x2d, 0x2e, 0x4d, 0x71, 0x53, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x43, 0x6f, 0x6e,
	0x73, 0x75, 0x6d, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x4f, 0x66, 0x66,
	0x73, 0x65, 0x74, 0x52, 0x65, 0x73, 0x65, 0x74, 0x52, 0x0f, 0x4f, 0x66, 0x66, 0x73, 0x65, 0x74,
	0x52, 0x65, 0x73, 0x65, 0x74, 0x4d, 0x6f, 0x64, 0x65, 0x22, 0x31, 0x0a, 0x0b, 0x4f, 0x66, 0x66,
	0x73, 0x65, 0x74, 0x52, 0x65, 0x73, 0x65, 0x74, 0x12, 0x0c, 0x0a, 0x08, 0x45, 0x61, 0x72, 0x6c,
	0x69, 0x65, 0x73, 0x74, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x4c, 0x61, 0x74, 0x65, 0x73, 0x74,
	0x10, 0x01, 0x12, 0x08, 0x0a, 0x04, 0x4e, 0x6f, 0x6e, 0x65, 0x10, 0x02, 0x22, 0x47, 0x0a, 0x09,
	0x50, 0x61, 0x72, 0x74, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x54, 0x6f, 0x70,
	0x69, 0x63, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x54, 0x6f, 0x70, 0x69, 0x63, 0x12,
	0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e,
	0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x55, 0x72, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x55, 0x72, 0x6c, 0x22, 0xc0, 0x01, 0x0a, 0x18, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74,
	0x65, 0x72, 0x43, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x2e, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x4d, 0x71, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x35, 0x0a, 0x0a, 0x43, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x4d, 0x71, 0x53, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x2e, 0x43, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x73, 0x52, 0x0a, 0x43,
	0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x12, 0x3d, 0x0a, 0x0f, 0x46, 0x6f, 0x63,
	0x61, 0x6c, 0x50, 0x61, 0x72, 0x74, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x03, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x13, 0x2e, 0x4d, 0x71, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x50, 0x61,
	0x72, 0x74, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0f, 0x46, 0x6f, 0x63, 0x61, 0x6c, 0x50, 0x61,
	0x72, 0x74, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0x69, 0x0a, 0x17, 0x52, 0x65, 0x67, 0x69,
	0x73, 0x74, 0x65, 0x72, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x46, 0x6f, 0x63, 0x61, 0x6c, 0x54, 0x6f, 0x70, 0x69,
	0x63, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x46, 0x6f, 0x63, 0x61, 0x6c, 0x54, 0x6f,
	0x70, 0x69, 0x63, 0x12, 0x2e, 0x0a, 0x12, 0x4d, 0x61, 0x78, 0x50, 0x75, 0x73, 0x68, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x12, 0x4d, 0x61, 0x78, 0x50, 0x75, 0x73, 0x68, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x53,
	0x69, 0x7a, 0x65, 0x22, 0xaa, 0x02, 0x0a, 0x18, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72,
	0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x2e, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x12, 0x2e, 0x4d, 0x71, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x35, 0x0a, 0x0a, 0x43, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x4d, 0x71, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e,
	0x43, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x73, 0x52, 0x0a, 0x43, 0x72, 0x65,
	0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x12, 0x3d, 0x0a, 0x0f, 0x46, 0x6f, 0x63, 0x61, 0x6c,
	0x50, 0x61, 0x72, 0x74, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x13, 0x2e, 0x4d, 0x71, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x50, 0x61, 0x72, 0x74,
	0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0f, 0x46, 0x6f, 0x63, 0x61, 0x6c, 0x50, 0x61, 0x72, 0x74,
	0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x32, 0x0a, 0x14, 0x41, 0x6c, 0x6c, 0x6f, 0x77, 0x50,
	0x75, 0x73, 0x68, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x14, 0x41, 0x6c, 0x6c, 0x6f, 0x77, 0x50, 0x75, 0x73, 0x68, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x34, 0x0a, 0x15, 0x41, 0x6c,
	0x6c, 0x6f, 0x77, 0x50, 0x75, 0x73, 0x68, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x43, 0x6f,
	0x75, 0x6e, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x15, 0x41, 0x6c, 0x6c, 0x6f, 0x77,
	0x50, 0x75, 0x73, 0x68, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x43, 0x6f, 0x75, 0x6e, 0x74,
	0x22, 0xeb, 0x01, 0x0a, 0x12, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x6f, 0x70, 0x69, 0x63,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x54, 0x6f, 0x70, 0x69, 0x63,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x54, 0x6f, 0x70, 0x69, 0x63, 0x12, 0x51, 0x0a,
	0x09, 0x50, 0x61, 0x72, 0x74, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x33, 0x2e, 0x4d, 0x71, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x54, 0x6f, 0x70, 0x69, 0x63, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x50,
	0x61, 0x72, 0x74, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x44, 0x65,
	0x74, 0x61, 0x69, 0x6c, 0x73, 0x52, 0x09, 0x50, 0x61, 0x72, 0x74, 0x69, 0x74, 0x69, 0x6f, 0x6e,
	0x1a, 0x6c, 0x0a, 0x16, 0x50, 0x61, 0x72, 0x74, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x12, 0x24, 0x0a, 0x0d, 0x50, 0x61,
	0x72, 0x74, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0d, 0x50, 0x61, 0x72, 0x74, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x4e, 0x61, 0x6d, 0x65,
	0x12, 0x2c, 0x0a, 0x11, 0x52, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4e,
	0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x11, 0x52, 0x65, 0x70,
	0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x22, 0x86,
	0x01, 0x0a, 0x13, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x6f, 0x70, 0x69, 0x63, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2e, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x4d, 0x71, 0x53, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x08, 0x72, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3f, 0x0a, 0x10, 0x50, 0x61, 0x72, 0x74, 0x69, 0x74,
	0x69, 0x6f, 0x6e, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x13, 0x2e, 0x4d, 0x71, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x50, 0x61, 0x72, 0x74,
	0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x10, 0x50, 0x61, 0x72, 0x74, 0x69, 0x74, 0x69, 0x6f, 0x6e,
	0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x22, 0x60, 0x0a, 0x11, 0x51, 0x75, 0x65, 0x72, 0x79,
	0x54, 0x6f, 0x70, 0x69, 0x63, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x35, 0x0a, 0x0a,
	0x63, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x15, 0x2e, 0x4d, 0x71, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x43, 0x72, 0x65, 0x64,
	0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x73, 0x52, 0x0a, 0x63, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74,
	0x69, 0x61, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x54, 0x6f, 0x70, 0x69, 0x63, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x54, 0x6f, 0x70, 0x69, 0x63, 0x22, 0x85, 0x01, 0x0a, 0x12, 0x51, 0x75,
	0x65, 0x72, 0x79, 0x54, 0x6f, 0x70, 0x69, 0x63, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x2e, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x12, 0x2e, 0x4d, 0x71, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x3f, 0x0a, 0x10, 0x50, 0x61, 0x72, 0x74, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x44, 0x65, 0x74,
	0x61, 0x69, 0x6c, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x4d, 0x71, 0x53,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x50, 0x61, 0x72, 0x74, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x10, 0x50, 0x61, 0x72, 0x74, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c,
	0x73, 0x22, 0x2b, 0x0a, 0x13, 0x44, 0x65, 0x73, 0x74, 0x72, 0x6f, 0x79, 0x54, 0x6f, 0x70, 0x69,
	0x63, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x54, 0x6f, 0x70, 0x69,
	0x63, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x54, 0x6f, 0x70, 0x69, 0x63, 0x22, 0x46,
	0x0a, 0x14, 0x44, 0x65, 0x73, 0x74, 0x72, 0x6f, 0x79, 0x54, 0x6f, 0x70, 0x69, 0x63, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2e, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x4d, 0x71, 0x53, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x08, 0x72, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x52, 0x0a, 0x19, 0x55, 0x6e, 0x52, 0x65, 0x67, 0x69,
	0x73, 0x74, 0x65, 0x72, 0x43, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x35, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61,
	0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x4d, 0x71, 0x53, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x2e, 0x43, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x73, 0x52, 0x0a,
	0x63, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x22, 0x4c, 0x0a, 0x1a, 0x55, 0x6e,
	0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x43, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65, 0x72,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2e, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x4d, 0x71, 0x53,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x08,
	0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x52, 0x0a, 0x19, 0x55, 0x6e, 0x52, 0x65,
	0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x65, 0x72, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x35, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74,
	0x69, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x4d, 0x71, 0x53, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x2e, 0x43, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x73,
	0x52, 0x0a, 0x63, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x22, 0x4c, 0x0a, 0x1a,
	0x55, 0x6e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63,
	0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2e, 0x0a, 0x08, 0x72, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x4d,
	0x71, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x52, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x23, 0x0a, 0x07, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22,
	0x72, 0x0a, 0x12, 0x50, 0x75, 0x73, 0x68, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x35, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74,
	0x69, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x4d, 0x71, 0x53, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x2e, 0x43, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x73,
	0x52, 0x0a, 0x63, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x12, 0x25, 0x0a, 0x04,
	0x4d, 0x73, 0x67, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x4d, 0x71, 0x53,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x04, 0x4d,
	0x73, 0x67, 0x73, 0x22, 0x45, 0x0a, 0x13, 0x50, 0x75, 0x73, 0x68, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2e, 0x0a, 0x08, 0x72, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x4d,
	0x71, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x52, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x50, 0x0a, 0x12, 0x50, 0x75,
	0x6c, 0x6c, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x1a, 0x0a, 0x01, 0x5f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x4d, 0x71,
	0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x41, 0x63, 0x6b, 0x52, 0x00, 0x12, 0x1e, 0x0a, 0x0a,
	0x57, 0x69, 0x6e, 0x64, 0x6f, 0x77, 0x53, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x0a, 0x57, 0x69, 0x6e, 0x64, 0x6f, 0x77, 0x53, 0x69, 0x7a, 0x65, 0x22, 0x6c, 0x0a, 0x13,
	0x50, 0x75, 0x6c, 0x6c, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x2e, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x4d, 0x71, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x25, 0x0a, 0x04, 0x4d, 0x73, 0x67, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x11, 0x2e, 0x4d, 0x71, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x52, 0x04, 0x4d, 0x73, 0x67, 0x73, 0x22, 0xb4, 0x02, 0x0a, 0x16, 0x4d,
	0x61, 0x6e, 0x61, 0x67, 0x65, 0x50, 0x61, 0x72, 0x74, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x54, 0x6f, 0x70, 0x69, 0x63, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x54, 0x6f, 0x70, 0x69, 0x63, 0x12, 0x4c, 0x0a, 0x0a, 0x4d,
	0x61, 0x6e, 0x61, 0x67, 0x65, 0x4d, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x2c, 0x2e, 0x4d, 0x71, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x4d, 0x61, 0x6e, 0x61, 0x67,
	0x65, 0x50, 0x61, 0x72, 0x74, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x2e, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x4d, 0x6f, 0x64, 0x65, 0x73, 0x52, 0x0a, 0x4d,
	0x61, 0x6e, 0x61, 0x67, 0x65, 0x4d, 0x6f, 0x64, 0x65, 0x12, 0x3a, 0x0a, 0x0a, 0x43, 0x72, 0x65,
	0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e,
	0x4d, 0x71, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x43, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74,
	0x69, 0x61, 0x6c, 0x73, 0x48, 0x00, 0x52, 0x0a, 0x43, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69,
	0x61, 0x6c, 0x88, 0x01, 0x01, 0x12, 0x30, 0x0a, 0x13, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x50,
	0x61, 0x72, 0x74, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x13, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x50, 0x61, 0x72, 0x74, 0x69, 0x74,
	0x69, 0x6f, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x39, 0x0a, 0x0b, 0x4d, 0x61, 0x6e, 0x61, 0x67,
	0x65, 0x4d, 0x6f, 0x64, 0x65, 0x73, 0x12, 0x07, 0x0a, 0x03, 0x41, 0x64, 0x64, 0x10, 0x00, 0x12,
	0x07, 0x0a, 0x03, 0x44, 0x65, 0x6c, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x46, 0x6f, 0x6c, 0x6c,
	0x6f, 0x77, 0x10, 0x02, 0x12, 0x0c, 0x0a, 0x08, 0x55, 0x6e, 0x46, 0x6f, 0x6c, 0x6c, 0x6f, 0x77,
	0x10, 0x03, 0x42, 0x0d, 0x0a, 0x0b, 0x5f, 0x43, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61,
	0x6c, 0x22, 0x84, 0x01, 0x0a, 0x17, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x50, 0x61, 0x72, 0x74,
	0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2e, 0x0a,
	0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x12, 0x2e, 0x4d, 0x71, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x52, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x39, 0x0a,
	0x0d, 0x4e, 0x6f, 0x77, 0x50, 0x61, 0x72, 0x74, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x4d, 0x71, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e,
	0x50, 0x61, 0x72, 0x74, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0d, 0x4e, 0x6f, 0x77, 0x50, 0x61,
	0x72, 0x74, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x32, 0xa0, 0x07, 0x0a, 0x0c, 0x4d, 0x71, 0x53,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x43, 0x61, 0x6c, 0x6c, 0x12, 0x5b, 0x0a, 0x10, 0x52, 0x65, 0x67,
	0x69, 0x73, 0x74, 0x65, 0x72, 0x43, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65, 0x72, 0x12, 0x21, 0x2e,
	0x4d, 0x71, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65,
	0x72, 0x43, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x22, 0x2e, 0x4d, 0x71, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x52, 0x65, 0x67, 0x69,
	0x73, 0x74, 0x65, 0x72, 0x43, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x5b, 0x0a, 0x10, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74,
	0x65, 0x72, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x65, 0x72, 0x12, 0x21, 0x2e, 0x4d, 0x71, 0x53,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x50, 0x72,
	0x6f, 0x64, 0x75, 0x63, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e,
	0x4d, 0x71, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65,
	0x72, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x12, 0x4c, 0x0a, 0x0b, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x6f, 0x70,
	0x69, 0x63, 0x12, 0x1c, 0x2e, 0x4d, 0x71, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x54, 0x6f, 0x70, 0x69, 0x63, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x1d, 0x2e, 0x4d, 0x71, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x54, 0x6f, 0x70, 0x69, 0x63, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x12, 0x49, 0x0a, 0x0a, 0x51, 0x75, 0x65, 0x72, 0x79, 0x54, 0x6f, 0x70, 0x69, 0x63, 0x12,
	0x1b, 0x2e, 0x4d, 0x71, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79,
	0x54, 0x6f, 0x70, 0x69, 0x63, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x4d,
	0x71, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x54, 0x6f, 0x70,
	0x69, 0x63, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x4f, 0x0a, 0x0c,
	0x44, 0x65, 0x73, 0x74, 0x72, 0x6f, 0x79, 0x54, 0x6f, 0x70, 0x69, 0x63, 0x12, 0x1d, 0x2e, 0x4d,
	0x71, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x44, 0x65, 0x73, 0x74, 0x72, 0x6f, 0x79, 0x54,
	0x6f, 0x70, 0x69, 0x63, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x4d, 0x71,
	0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x44, 0x65, 0x73, 0x74, 0x72, 0x6f, 0x79, 0x54, 0x6f,
	0x70, 0x69, 0x63, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x58, 0x0a,
	0x0f, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x50, 0x61, 0x72, 0x74, 0x69, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x20, 0x2e, 0x4d, 0x71, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x4d, 0x61, 0x6e, 0x61,
	0x67, 0x65, 0x50, 0x61, 0x72, 0x74, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x21, 0x2e, 0x4d, 0x71, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x4d, 0x61,
	0x6e, 0x61, 0x67, 0x65, 0x50, 0x61, 0x72, 0x74, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x61, 0x0a, 0x12, 0x55, 0x6e, 0x52, 0x65, 0x67,
	0x69, 0x73, 0x74, 0x65, 0x72, 0x43, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65, 0x72, 0x12, 0x23, 0x2e,
	0x4d, 0x71, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x55, 0x6e, 0x52, 0x65, 0x67, 0x69, 0x73,
	0x74, 0x65, 0x72, 0x43, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x24, 0x2e, 0x4d, 0x71, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x55, 0x6e,
	0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x43, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65, 0x72,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x61, 0x0a, 0x12, 0x55, 0x6e,
	0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x65, 0x72,
	0x12, 0x23, 0x2e, 0x4d, 0x71, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x55, 0x6e, 0x52, 0x65,
	0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x65, 0x72, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e, 0x4d, 0x71, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x2e, 0x55, 0x6e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x50, 0x72, 0x6f, 0x64, 0x75,
	0x63, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x30, 0x0a,
	0x09, 0x48, 0x65, 0x61, 0x72, 0x74, 0x62, 0x65, 0x61, 0x74, 0x12, 0x0d, 0x2e, 0x4d, 0x71, 0x53,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x41, 0x63, 0x6b, 0x1a, 0x12, 0x2e, 0x4d, 0x71, 0x53, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12,
	0x4c, 0x0a, 0x0b, 0x50, 0x75, 0x6c, 0x6c, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x1c,
	0x2e, 0x4d, 0x71, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x50, 0x75, 0x6c, 0x6c, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x4d,
	0x71, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x50, 0x75, 0x6c, 0x6c, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x4c, 0x0a,
	0x0b, 0x50, 0x75, 0x73, 0x68, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x1c, 0x2e, 0x4d,
	0x71, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x50, 0x75, 0x73, 0x68, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x4d, 0x71, 0x53,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x50, 0x75, 0x73, 0x68, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x03, 0x5a, 0x01, 0x2e,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_MqServerRpc_proto_rawDescOnce sync.Once
	file_MqServerRpc_proto_rawDescData = file_MqServerRpc_proto_rawDesc
)

func file_MqServerRpc_proto_rawDescGZIP() []byte {
	file_MqServerRpc_proto_rawDescOnce.Do(func() {
		file_MqServerRpc_proto_rawDescData = protoimpl.X.CompressGZIP(file_MqServerRpc_proto_rawDescData)
	})
	return file_MqServerRpc_proto_rawDescData
}

var file_MqServerRpc_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_MqServerRpc_proto_msgTypes = make([]protoimpl.MessageInfo, 26)
var file_MqServerRpc_proto_goTypes = []interface{}{
	(Credentials_CredentialsIdentity)(0),              // 0: MqServer.Credentials.CredentialsIdentity
	(Response_Mode)(0),                                // 1: MqServer.Response.Mode
	(RegisterConsumerRequest_OffsetReset)(0),          // 2: MqServer.RegisterConsumerRequest.OffsetReset
	(ManagePartitionRequest_ManageModes)(0),           // 3: MqServer.ManagePartitionRequest.ManageModes
	(*Credentials)(nil),                               // 4: MqServer.Credentials
	(*Ack)(nil),                                       // 5: MqServer.Ack
	(*Response)(nil),                                  // 6: MqServer.Response
	(*RegisterConsumerRequest)(nil),                   // 7: MqServer.RegisterConsumerRequest
	(*Partition)(nil),                                 // 8: MqServer.Partition
	(*RegisterConsumerResponse)(nil),                  // 9: MqServer.RegisterConsumerResponse
	(*RegisterProducerRequest)(nil),                   // 10: MqServer.RegisterProducerRequest
	(*RegisterProducerResponse)(nil),                  // 11: MqServer.RegisterProducerResponse
	(*CreateTopicRequest)(nil),                        // 12: MqServer.CreateTopicRequest
	(*CreateTopicResponse)(nil),                       // 13: MqServer.CreateTopicResponse
	(*QueryTopicRequest)(nil),                         // 14: MqServer.QueryTopicRequest
	(*QueryTopicResponse)(nil),                        // 15: MqServer.QueryTopicResponse
	(*DestroyTopicRequest)(nil),                       // 16: MqServer.DestroyTopicRequest
	(*DestroyTopicResponse)(nil),                      // 17: MqServer.DestroyTopicResponse
	(*UnRegisterConsumerRequest)(nil),                 // 18: MqServer.UnRegisterConsumerRequest
	(*UnRegisterConsumerResponse)(nil),                // 19: MqServer.UnRegisterConsumerResponse
	(*UnRegisterProducerRequest)(nil),                 // 20: MqServer.UnRegisterProducerRequest
	(*UnRegisterProducerResponse)(nil),                // 21: MqServer.UnRegisterProducerResponse
	(*Message)(nil),                                   // 22: MqServer.Message
	(*PushMessageRequest)(nil),                        // 23: MqServer.PushMessageRequest
	(*PushMessageResponse)(nil),                       // 24: MqServer.PushMessageResponse
	(*PullMessageRequest)(nil),                        // 25: MqServer.PullMessageRequest
	(*PullMessageResponse)(nil),                       // 26: MqServer.PullMessageResponse
	(*ManagePartitionRequest)(nil),                    // 27: MqServer.ManagePartitionRequest
	(*ManagePartitionResponse)(nil),                   // 28: MqServer.ManagePartitionResponse
	(*CreateTopicRequest_PartitionCreateDetails)(nil), // 29: MqServer.CreateTopicRequest.PartitionCreateDetails
}
var file_MqServerRpc_proto_depIdxs = []int32{
	0,  // 0: MqServer.Credentials.Identity:type_name -> MqServer.Credentials.CredentialsIdentity
	4,  // 1: MqServer.Ack.credential:type_name -> MqServer.Credentials
	1,  // 2: MqServer.Response.mode:type_name -> MqServer.Response.Mode
	2,  // 3: MqServer.RegisterConsumerRequest.OffsetResetMode:type_name -> MqServer.RegisterConsumerRequest.OffsetReset
	6,  // 4: MqServer.RegisterConsumerResponse.response:type_name -> MqServer.Response
	4,  // 5: MqServer.RegisterConsumerResponse.Credential:type_name -> MqServer.Credentials
	8,  // 6: MqServer.RegisterConsumerResponse.FocalPartitions:type_name -> MqServer.Partition
	6,  // 7: MqServer.RegisterProducerResponse.response:type_name -> MqServer.Response
	4,  // 8: MqServer.RegisterProducerResponse.Credential:type_name -> MqServer.Credentials
	8,  // 9: MqServer.RegisterProducerResponse.FocalPartitions:type_name -> MqServer.Partition
	29, // 10: MqServer.CreateTopicRequest.Partition:type_name -> MqServer.CreateTopicRequest.PartitionCreateDetails
	6,  // 11: MqServer.CreateTopicResponse.response:type_name -> MqServer.Response
	8,  // 12: MqServer.CreateTopicResponse.PartitionDetails:type_name -> MqServer.Partition
	4,  // 13: MqServer.QueryTopicRequest.credential:type_name -> MqServer.Credentials
	6,  // 14: MqServer.QueryTopicResponse.response:type_name -> MqServer.Response
	8,  // 15: MqServer.QueryTopicResponse.PartitionDetails:type_name -> MqServer.Partition
	6,  // 16: MqServer.DestroyTopicResponse.response:type_name -> MqServer.Response
	4,  // 17: MqServer.UnRegisterConsumerRequest.credential:type_name -> MqServer.Credentials
	6,  // 18: MqServer.UnRegisterConsumerResponse.response:type_name -> MqServer.Response
	4,  // 19: MqServer.UnRegisterProducerRequest.credential:type_name -> MqServer.Credentials
	6,  // 20: MqServer.UnRegisterProducerResponse.response:type_name -> MqServer.Response
	4,  // 21: MqServer.PushMessageRequest.credential:type_name -> MqServer.Credentials
	22, // 22: MqServer.PushMessageRequest.Msgs:type_name -> MqServer.Message
	6,  // 23: MqServer.PushMessageResponse.response:type_name -> MqServer.Response
	5,  // 24: MqServer.PullMessageRequest._:type_name -> MqServer.Ack
	6,  // 25: MqServer.PullMessageResponse.response:type_name -> MqServer.Response
	22, // 26: MqServer.PullMessageResponse.Msgs:type_name -> MqServer.Message
	3,  // 27: MqServer.ManagePartitionRequest.ManageMode:type_name -> MqServer.ManagePartitionRequest.ManageModes
	4,  // 28: MqServer.ManagePartitionRequest.Credential:type_name -> MqServer.Credentials
	6,  // 29: MqServer.ManagePartitionResponse.response:type_name -> MqServer.Response
	8,  // 30: MqServer.ManagePartitionResponse.NowPartitions:type_name -> MqServer.Partition
	7,  // 31: MqServer.MqServerCall.RegisterConsumer:input_type -> MqServer.RegisterConsumerRequest
	10, // 32: MqServer.MqServerCall.RegisterProducer:input_type -> MqServer.RegisterProducerRequest
	12, // 33: MqServer.MqServerCall.CreateTopic:input_type -> MqServer.CreateTopicRequest
	14, // 34: MqServer.MqServerCall.QueryTopic:input_type -> MqServer.QueryTopicRequest
	16, // 35: MqServer.MqServerCall.DestroyTopic:input_type -> MqServer.DestroyTopicRequest
	27, // 36: MqServer.MqServerCall.ManagePartition:input_type -> MqServer.ManagePartitionRequest
	18, // 37: MqServer.MqServerCall.UnRegisterConsumer:input_type -> MqServer.UnRegisterConsumerRequest
	20, // 38: MqServer.MqServerCall.UnRegisterProducer:input_type -> MqServer.UnRegisterProducerRequest
	5,  // 39: MqServer.MqServerCall.Heartbeat:input_type -> MqServer.Ack
	25, // 40: MqServer.MqServerCall.PullMessage:input_type -> MqServer.PullMessageRequest
	23, // 41: MqServer.MqServerCall.PushMessage:input_type -> MqServer.PushMessageRequest
	9,  // 42: MqServer.MqServerCall.RegisterConsumer:output_type -> MqServer.RegisterConsumerResponse
	11, // 43: MqServer.MqServerCall.RegisterProducer:output_type -> MqServer.RegisterProducerResponse
	13, // 44: MqServer.MqServerCall.CreateTopic:output_type -> MqServer.CreateTopicResponse
	15, // 45: MqServer.MqServerCall.QueryTopic:output_type -> MqServer.QueryTopicResponse
	17, // 46: MqServer.MqServerCall.DestroyTopic:output_type -> MqServer.DestroyTopicResponse
	28, // 47: MqServer.MqServerCall.ManagePartition:output_type -> MqServer.ManagePartitionResponse
	19, // 48: MqServer.MqServerCall.UnRegisterConsumer:output_type -> MqServer.UnRegisterConsumerResponse
	21, // 49: MqServer.MqServerCall.UnRegisterProducer:output_type -> MqServer.UnRegisterProducerResponse
	6,  // 50: MqServer.MqServerCall.Heartbeat:output_type -> MqServer.Response
	26, // 51: MqServer.MqServerCall.PullMessage:output_type -> MqServer.PullMessageResponse
	24, // 52: MqServer.MqServerCall.PushMessage:output_type -> MqServer.PushMessageResponse
	42, // [42:53] is the sub-list for method output_type
	31, // [31:42] is the sub-list for method input_type
	31, // [31:31] is the sub-list for extension type_name
	31, // [31:31] is the sub-list for extension extendee
	0,  // [0:31] is the sub-list for field type_name
}

func init() { file_MqServerRpc_proto_init() }
func file_MqServerRpc_proto_init() {
	if File_MqServerRpc_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_MqServerRpc_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Credentials); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_MqServerRpc_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Ack); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_MqServerRpc_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_MqServerRpc_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterConsumerRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_MqServerRpc_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Partition); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_MqServerRpc_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterConsumerResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_MqServerRpc_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterProducerRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_MqServerRpc_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterProducerResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_MqServerRpc_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateTopicRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_MqServerRpc_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateTopicResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_MqServerRpc_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryTopicRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_MqServerRpc_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryTopicResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_MqServerRpc_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DestroyTopicRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_MqServerRpc_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DestroyTopicResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_MqServerRpc_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UnRegisterConsumerRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_MqServerRpc_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UnRegisterConsumerResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_MqServerRpc_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UnRegisterProducerRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_MqServerRpc_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UnRegisterProducerResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_MqServerRpc_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Message); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_MqServerRpc_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PushMessageRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_MqServerRpc_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PushMessageResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_MqServerRpc_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PullMessageRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_MqServerRpc_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PullMessageResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_MqServerRpc_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ManagePartitionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_MqServerRpc_proto_msgTypes[24].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ManagePartitionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_MqServerRpc_proto_msgTypes[25].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateTopicRequest_PartitionCreateDetails); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_MqServerRpc_proto_msgTypes[1].OneofWrappers = []interface{}{}
	file_MqServerRpc_proto_msgTypes[23].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_MqServerRpc_proto_rawDesc,
			NumEnums:      4,
			NumMessages:   26,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_MqServerRpc_proto_goTypes,
		DependencyIndexes: file_MqServerRpc_proto_depIdxs,
		EnumInfos:         file_MqServerRpc_proto_enumTypes,
		MessageInfos:      file_MqServerRpc_proto_msgTypes,
	}.Build()
	File_MqServerRpc_proto = out.File
	file_MqServerRpc_proto_rawDesc = nil
	file_MqServerRpc_proto_goTypes = nil
	file_MqServerRpc_proto_depIdxs = nil
}
